development:
  adapter: postgresql
  encoding: unicode
  database: jobber_development
  pool: 5
  username: austin
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: jobber_test
  pool: 5
  username: austin
  password:
